server:
  port: 8080

spring:
  application:
    name: patient-notes-service

  data:
    mongodb:
      host: patient-notes-db
      port: 27017
      database: ${PATIENT_NOTES_DB_NAME}
      username: ${PATIENT_NOTES_DB_USER}
      password: ${PATIENT_NOTES_DB_PASSWORD}
      authentication-database: ${PATIENT_NOTES_DB_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          sign-in-key: ${jwt.secret}

jwt:
  secret: {JWT_SECRET}